### ISSUE TITLE
How to change style of product list?

### ISSUE THREAD

**Issue by KeepGrowingHere** [KeepGrowingHere/e-commerce-site#3]
Please solve this issue asap.

**Comment by AllTwinkleStars** [comment]
You can modify the stylesheet of the "span" tag that includes product names.

**Comment by KeepGrowingHere** [comment]
> You can modify the stylesheet of the "span" tag that includes product names.
Thanks for your reply.

**Comment by KeepGrowingHere** [comment]
Thanks for AllTwinkleStars's great effort.
